### ISSUE TITLE
Plotting smooth gene expression trends along lineages

### ISSUE THREAD

**Issue by sidrahmaryam** [theislab/cellrank_notebooks#27]
Hello,
Thank you for the wonderful pipeline.

I am facing an issue while running the section of 'basics', **plot smooth gene expression trends along lineages.**

As before that we need to run `scv.tl.diffmap(adata)`
When i run it, it shows an error :
_**TypeError: '>=' not supported between instances of 'tuple' and 'int'**_

Please help as what could be the possible reason for that. I have already run dynamical mode of scVelo.

Thank you for the help in advance.

**Comment by michalk8** [comment]
Hi @sidrahmaryam ,
it's more of a scanpy issue, since scvelo just imports diffmap from there: https://github.com/theislab/scvelo/blob/master/scvelo/tools/__init__.py#L12
I remember encountering this error myself using `scanpy==1.5.*` and updating to `scanpy==1.6.0` seems to have fixed it.
Let me know if this helps - if not, please try opening an here: https://github.com/theislab/scanpy/issues

**Comment by sidrahmaryam** [comment]
Thank you so much for the suggestion. 

Yes it did solve. 💯

**Comment by michalk8** [comment]
Glad that it worked.
