### ISSUE TITLE
Pancreas basic tutorial - Gene expression trends: Var annotations not found

### ISSUE THREAD

**Issue by le-ander** [theislab/cellrank_notebooks#29]
I'm trying out some example from the notebook and got stuck in the gene dynamics heatmap section right at the bottom of the turoial. In my adata object, I cannot find the key `adata.var['to TERMINAL_STATE']` (TERMINAL_STATE being Alpha in the tutorial. In my adata.var I only have the columns `to TERMINAL_STATE corr` and `to TERMINAL_STATE qval`

Did I maybe miss a step in the pipeline that would have created the missing column?

This is the section I am referring to:

![Screenshot 2020-11-24 at 13 40 26](https://user-images.githubusercontent.com/20015434/100095354-a11e8b80-2e5a-11eb-946c-d71b92295cda.png)

**Comment by michalk8** [comment]
Hi @le-ander ,
you're right, the tutorial notebooks are slightly outdated (my CI should've let me know, but no more Travis credits).
I will regenerate it now (btw I recommend the examples, since they are always up-to-date).
As for the keys, in https://github.com/theislab/cellrank/pull/437, `to TERMINAL_STATE` was rename to `to TERMINAL_STATE corr` to better distinguish the columns (like the `qval` or `ci low` and `ci high`).

**Comment by le-ander** [comment]
Thanks for the clarification! I guess now that you have the qvalues readily available as well you could also use the top 100 genes by qvalue, which would give you a mix of positively and negatively correlated genes.

I find the negatively correlated ones also interesting as the turning off of certain genes can also be considered as a lineage definition. Any thoughts on this? also @Marius1311

**Comment by Marius1311** [comment]
I think for the tutorial it's fine as it stands because we're only interested in showing the functionality, but you're right, for general applications, it can be quite interesting to look at down-regulation as well. 

We don't really do any sorting at the moment, we just add the key to `.var`, so it's really up to the user which genes they are interested in .

**Comment by michalk8** [comment]
I'm assuming this is has been solved (the tutorials have been regenerated), feel free to reopen.
